ifeq ($(TARGET_BOOTLOADER_BOARD_NAME),zoom2)
include $(call first-makefiles-under,$(call my-dir))

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := bridged
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_SRC_FILES := recovery/sbin/bridged
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := cexec.out
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_SRC_FILES := recovery/sbin/cexec.out
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := omap-edpd.elf
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_SRC_FILES := recovery/sbin/omap-edpd.elf
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := refresh.sh
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_SRC_FILES := recovery/sbin/refresh.sh
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := baseimage.dof
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/etc/dsp
LOCAL_SRC_FILES := recovery/etc/dsp/baseimage.dof
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := default_waveform.bin
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/etc/dsp
LOCAL_SRC_FILES := recovery/etc/dsp/default_waveform.bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := subframeip_snode_dsp.dll64P
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/etc/dsp
LOCAL_SRC_FILES := recovery/etc/dsp/subframeip_snode_dsp.dll64P
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := EpdWaveform
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/etc/
LOCAL_SRC_FILES := recovery/etc/EpdWaveform
include $(BUILD_PREBUILT)
endif
